availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/VITE_TLDRAW_LICENSE_KEY/versions/latest
      env: VITE_TLDRAW_LICENSE_KEY

steps:
  # Step 0: Verify the secret is actually injected (prints only length)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['VITE_TLDRAW_LICENSE_KEY']
    args:
      - '-c'
      - 'echo "tldraw key length: ${#VITE_TLDRAW_LICENSE_KEY}"; test -n "$VITE_TLDRAW_LICENSE_KEY"'
    id: 'check-secret'

  # Step 1: Build the Docker image (passes secret into build arg)
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['VITE_TLDRAW_LICENSE_KEY']
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_IMAGE_NAME}:latest'
      - '--build-arg'
      - 'VITE_TLDRAW_LICENSE_KEY=$$VITE_TLDRAW_LICENSE_KEY'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-image'

  # Step 2: Push SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:${SHORT_SHA}']
    id: 'push-image-sha'

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:latest']
    id: 'push-image-latest'

images:
  - '${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_IMAGE_NAME}:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: 'gcr.io/$PROJECT_ID/rubydraw-frontend'